apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: 876606637086.dkr.ecr.us-east-1.amazonaws.com/mfejzic:latest
    ports: 80
    - containerPort: 80






























# apiVersion: v1
# kind: pod
# metadata: 
#   name: app
# spec
#   replicas: 3  
#   selector: 
#     matchLabels:
#       app: app
#   template:
#     metadata:
#       labels:
#         app: app
#     spec:
#       containers:
#         - name: app
#           image: 876606637086.dkr.ecr.us-east-1.amazonaws.com/mfejzic:latest
#           ports:
#             - containerPort: 80
#           env:
#             - name: FLASK_ENV
#               value: "production"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-service
# spec:
#   selector:
#     app: app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: LoadBalancer



#   apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig
# metadata:
#   name: my-cluster
#   region: region-code
# managedNodeGroups:
# - name: my-mng
#   launchTemplate:
#     id: lt-id
#     version: "1"